__date__ = "05 Nov 2022"
__answer__ = 4613732

__problem__ = """
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

# ---------------------------------------------------------


# Solution 1:
def fibevensum(mx):
    evensum = 0
    x, y = 0, 1
    while y < mx:
        if y%2 == 0: evensum += y
        x, y = y, x+y
    return evensum
print(fibevensum(int(input()))) # four million or another number entry
# returns 4613732 if the number four million is entered